algo = input('Digite Algo: ')
print('O tipo Primitivo é:', type(algo))
print('Só tem espaços?', algo.isspace())
print('é alfabetico:', algo.isalpha())
print('é alfanumerico', algo.isalnum())
print('esta em maiuscula', algo.isupper())
print('esta em minusculas', algo.islower())
